//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int id { get; set; }
        public string HomeAddress { get; set; }
        public string Office { get; set; }
        public string Person { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
