
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Lsm.Data.Repositories.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Author
{

    public System.Guid Id { get; set; }

    public string CatalogueId { get; set; }

    public string Author1 { get; set; }

}

}
