//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int Id { get; set; }
        public Nullable<System.Guid> RowGUID { get; set; }
        public string InventoryReferenceNo { get; set; }
        public int EmisCode { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
