//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int id { get; set; }
        public System.Guid RowGuid { get; set; }
        public string Name { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string Manager { get; set; }
        public string ParentBranch { get; set; }
        public bool IsActive { get; set; }
        public bool IsDistrict { get; set; }
        public bool IsCircuit { get; set; }
        public System.Data.Entity.Spatial.DbGeography LocationSpatial { get; set; }
        public string LocationSpatialText { get; set; }
        public string StAddress { get; set; }
    }
}
