//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public System.Guid RowGuId { get; set; }
        public int EmisCode { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] Image1 { get; set; }
        public byte[] Image128px { get; set; }
    }
}
