//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceSurvey
    {
        public System.Guid Id { get; set; }
        public string InterfaceKey { get; set; }
        public string SurveyKey { get; set; }
        public string EntityType { get; set; }
        public string AffectedEntities { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime ExpiresOn { get; set; }
        public string Label { get; set; }
        public string Curator { get; set; }
        public string Data_001 { get; set; }
        public string Data_002 { get; set; }
        public string Data_003 { get; set; }
        public string Data_004 { get; set; }
        public string Data_005 { get; set; }
        public Nullable<bool> IsEffective { get; set; }
    }
}
