//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailbox
    {
        public int Id { get; set; }
        public System.Guid RowGuid { get; set; }
        public string Name { get; set; }
        public string Directorate { get; set; }
        public string Group { get; set; }
        public string Administrator { get; set; }
        public string Owner { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
