//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionLookup
    {
        public int id { get; set; }
        public System.Guid RowGuid { get; set; }
        public string Position { get; set; }
        public int Rank { get; set; }
        public string RankFlag { get; set; }
        public int Level { get; set; }
        public Nullable<int> Directorate { get; set; }
    }
}
