//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepient
    {
        public int Id { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<int> EmisCode { get; set; }
        public string Email { get; set; }
        public int MailGroup { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
