//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public int Id { get; set; }
        public System.Guid InstanceId { get; set; }
        public string ReqNO { get; set; }
        public string EmisToken { get; set; }
        public string Calendar { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<byte> GrFrom { get; set; }
        public Nullable<byte> GrTo { get; set; }
        public string State { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string WINumber { get; set; }
    }
}
