//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAccountSetting
    {
        public int Id { get; set; }
        public int EmisCode { get; set; }
        public System.Guid Person { get; set; }
        public string UserId { get; set; }
        public int IsPublic { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int IsActive { get; set; }
        public string Role { get; set; }
        public string Email { get; set; }
        public string RoleId { get; set; }
    }
}
