//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoE.Lsm.Data.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMailbox
    {
        public System.Guid RowGuid { get; set; }
        public string Name { get; set; }
        public string DirectorateName { get; set; }
        public int GroupId { get; set; }
        public string DirectorateManager { get; set; }
        public string GroupName { get; set; }
        public string GroupAdministrator { get; set; }
        public bool IsGroupActive { get; set; }
        public string MailboxAdministrator { get; set; }
        public string MailboxOwner { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int ActiveUsers { get; set; }
        public int NonActiveUsers { get; set; }
    }
}
