
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Quota.Repositories.Data.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Catalogue
{

    public System.Guid Id { get; set; }

    public string Title { get; set; }

    public string ISBN { get; set; }

    public string ISBN13 { get; set; }

    public string Publisher { get; set; }

    public string Author { get; set; }

    public string Language { get; set; }

    public string Category { get; set; }

    public int SubjectCode { get; set; }

    public int Grade { get; set; }

    public decimal Price { get; set; }

    public System.DateTime EffDate { get; set; }

    public Nullable<System.DateTime> ExpDate { get; set; }

}

}
