
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Quota.Repositories.Data.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Inventory
{

    public int id { get; set; }

    public System.Guid InstanceId { get; set; }

    public string ParentEntity { get; set; }

    public int Sub_Code { get; set; }

    public string EmisCode { get; set; }

    public int Class_Enr { get; set; }

    public int Subj_Enr { get; set; }

    public int Teacher_Enr { get; set; }

    public int CategoryCD { get; set; }

    public string TL_Ratio { get; set; }

    public System.DateTime CreationDate { get; set; }

    public System.DateTime LastModifiedDate { get; set; }

    public bool IsBookmark { get; set; }

    public string OrderNo { get; set; }

    public decimal Price { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<int> Quota { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }

    public string BookYear { get; set; }

}

}
