
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Quota.Repositories.Data.EF
{

using System;
    using System.Collections.Generic;
    
public partial class InventoryRequest
{

    public int Id { get; set; }

    public Nullable<System.Guid> InstanceId { get; set; }

    public string ReqId { get; set; }

    public string ParentEntityId { get; set; }

    public int Quantity { get; set; }

    public int CategoryCD { get; set; }

    public string EmisToken { get; set; }

    public System.DateTime CreationDate { get; set; }

    public System.DateTime LastModifiedDate { get; set; }

    public Nullable<decimal> Price { get; set; }

    public decimal TotalPrice { get; set; }

}

}
