
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Quota.Repositories.Data.EF
{

using System;
    using System.Collections.Generic;
    
public partial class req_vwOrderItems
{

    public int id { get; set; }

    public string ISBN { get; set; }

    public int SubjCode { get; set; }

    public int EmisCode { get; set; }

    public Nullable<int> Enrolment { get; set; }

    public Nullable<int> Qty1 { get; set; }

    public Nullable<int> Qty2 { get; set; }

    public string ItemName { get; set; }

    public string SubjectName { get; set; }

    public string BookYear { get; set; }

    public string Author { get; set; }

    public int Grade { get; set; }

    public decimal Price { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }

    public string ReqId { get; set; }

    public Nullable<int> Quota { get; set; }

}

}
