
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Quota.Repositories.Data.EF
{

using System;
    using System.Collections.Generic;
    
public partial class ReqStatu
{

    public byte StatusID { get; set; }

    public string StatusDescription { get; set; }

    public bool Editable { get; set; }

    public bool Recallable { get; set; }

}

}
