
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Quota.Repositories.Data.EF
{

using System;
    using System.Collections.Generic;
    
public partial class School
{

    public int Id { get; set; }

    public System.Guid RowGuid { get; set; }

    public int EmisCode { get; set; }

    public string Name { get; set; }

    public string Phase { get; set; }

    public string Sector { get; set; }

    public string Type { get; set; }

    public string Initials { get; set; }

    public string PrincipalLastName { get; set; }

    public string PrincipalCellphone { get; set; }

    public string TownshipVillage { get; set; }

    public string Suburb { get; set; }

    public string Town { get; set; }

    public string Telephone { get; set; }

    public string Email { get; set; }

    public Nullable<int> Quintile { get; set; }

    public string EICircuit { get; set; }

    public string EIDistrict { get; set; }

    public string Manucipality { get; set; }

    public int Term { get; set; }

    public string DataYear { get; set; }

    public System.DateTime LastModifiedDate { get; set; }

    public bool IsActive { get; set; }

    public Nullable<int> CircuitCD { get; set; }

    public string PhaseDescription { get; set; }

}

}
