
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Quota.Repositories.Data.EF
{

using System;
    using System.Collections.Generic;
    
public partial class vw_RequisitionOrderItems
{

    public int id { get; set; }

    public string Requisitions { get; set; }

    public string ISBN { get; set; }

    public Nullable<int> OrderQty { get; set; }

    public string ItemName { get; set; }

    public string Publisher { get; set; }

    public string Author { get; set; }

    public string Language { get; set; }

    public string Category { get; set; }

    public string SubjectName { get; set; }

    public string Key { get; set; }

    public int Code { get; set; }

    public int Grade { get; set; }

    public decimal Price { get; set; }

    public int SubjCode { get; set; }

    public int EmisCode { get; set; }

    public int ClassEnrol { get; set; }

    public int SubjEnrol { get; set; }

    public Nullable<int> Qty { get; set; }

    public System.DateTime CreationDate { get; set; }

    public System.DateTime LastModifiedDate { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }

    public bool IsBookmarked { get; set; }

    public Nullable<int> ItemId { get; set; }

    public int TeacherCount { get; set; }

    public bool IsActive { get; set; }

    public string BookYear { get; set; }

    public int CategoryCD { get; set; }

    public Nullable<int> IsApproved { get; set; }

    public Nullable<int> Available { get; set; }

    public Nullable<int> Available2 { get; set; }

}

}
