
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoE.Quota.Repositories.Data.EF
{

using System;
    using System.Collections.Generic;
    
public partial class vwTotalSubcityPerCircuit
{

    public Nullable<int> CircuitCD { get; set; }

    public string EICircuit { get; set; }

    public Nullable<long> Schools { get; set; }

    public Nullable<int> Requisitions { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }

    public string BookYear { get; set; }

}

}
